name: Check Prettier Formatting

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
  pull_request:
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to Prettier.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Prettier
        run: sudo npm install --global prettier

      - name: Format with Prettier
        run: prettier --write .

      - name: Check formatting
        run: git diff --color --exit-code
